apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: react-app
      app.kubernetes.io/managed-by: argocd

images:
  - name: nexus-docker.example.com/my-group/react-app
    newTag: latest
